name: PR validation
on: pull_request
jobs:
  pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 4.11.1
          run_install: true
      - run: pnpm run build
